"""Add VehicleMaintenance and update Truck model

Revision ID: 0b6cb7dc7e97
Revises: 83fa31de45a8
Create Date: 2026-01-12 18:06:51.978760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b6cb7dc7e97'
down_revision = '83fa31de45a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_type', sa.String(length=50), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('odometer_reading', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['truck.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('odometer_km', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_maintenance_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('next_maintenance_km', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.drop_column('next_maintenance_km')
        batch_op.drop_column('last_maintenance_date')
        batch_op.drop_column('odometer_km')

    op.drop_table('vehicle_maintenance')
    # ### end Alembic commands ###
