"""Add Truck model and update LogisticsRoute

Revision ID: 273cc67c8481
Revises: 64c5907b9147
Create Date: 2026-01-12 15:39:43.214529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273cc67c8481'
down_revision = '64c5907b9147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('truck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('make_model', sa.String(length=100), nullable=True),
    sa.Column('capacity_kg', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lng', sa.Float(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_plate')
    )
    with op.batch_alter_table('logistics_route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('truck_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_logistics_route_truck_id', 'truck', ['truck_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logistics_route', schema=None) as batch_op:
        batch_op.drop_constraint('fk_logistics_route_truck_id', type_='foreignkey')
        batch_op.drop_column('truck_id')

    op.drop_table('truck')
    # ### end Alembic commands ###
