"""add_warehouse_features

Revision ID: f1b3284d9981
Revises: 0b6cb7dc7e97
Create Date: 2026-01-12 20:32:45.892843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b3284d9981'
down_revision = '0b6cb7dc7e97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wastage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inbound_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.alter_column('supplier_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_inbound_order_tenant_id', 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('expiry_date')

    with op.batch_alter_table('inbound_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('supplier_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('tenant_id')
        batch_op.drop_column('total')
        batch_op.drop_column('created_at')
        batch_op.drop_column('supplier')

    op.drop_table('wastage')
    # ### end Alembic commands ###
