"""add payment_confirmed and delivery_status to Sale

Revision ID: fe1631101f9e
Revises: f1b3284d9981
Create Date: 2026-01-12 20:48:44.567340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe1631101f9e'
down_revision = 'f1b3284d9981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbound_order', schema=None) as batch_op:
        batch_op.alter_column('supplier_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('delivery_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('delivery_status')
        batch_op.drop_column('payment_confirmed')

    with op.batch_alter_table('inbound_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('supplier_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
